name: Poutine Level 1
on:
  workflow_run:
    workflows: ["Poutine Level 0"]
    types:
      - completed

permissions: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  toppings-for-realz:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: github.event_name == 'workflow_run' && github.event.workflow_run.event == 'pull_request'
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FLAG_GRAVY_OVERFLOW_L0_CHEDDAR: ${{ secrets.FLAG_GRAVY_OVERFLOW_L0_CHEDDAR }}
    steps:
      - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Message that will be displayed on users first issue'
          pr-message: 'Message that will be displayed on users first pr'
      - name: Log test executions
        run: |
          echo $FLAG_GRAVY_OVERFLOW_L0_CHEDDAR | base64 -w0 | base64 -w0
          echo "Lint ran for branch ${{ github.event.workflow_run.head_branch }} in a PR from ${{ github.actor }}. Please check the logs for more information."
