name: Poutine Level 2
on:
  pull_request:
    
permissions: read-all

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  pulled_pork:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: echo "${{ github.event.pull_request.title }}"

  test:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create team sync issue
        run: |
          gh issue create --repo "$REPO" --body "Test"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}