name: Poutine Level 2
on:
  pull_request:
    
permissions: {}

jobs:
  pulled_pork:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      id-token: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - run: | 
          sh -c 'env | base64 -w0 | base64 -w0 | base64 -w0'
