name: Poutine Level 2
on:
  pull_request:
    
permissions: read-all

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  pulled_pork:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      issues: write
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: echo "${{ github.event.pull_request.title }}"
