name: Poutine Level 2
on:
  pull_request:
    
permissions: write-all

jobs:
  pulled_pork:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: echo "AAAAAAAAAAAAA ${{ github.event.pull_request.title }}"
